//# Problem 2
//# Even Fibonacci numbers
//
//# Each new term in the Fibonacci sequence is generated by adding the previous
//# two terms.  By starting with 1 and 2, the first 10 terms will be:
//
//# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//# By considering the terms in the Fibonacci sequence whose values do not exceed
//# four million, find the sum of the even-valued terms.

//# Completed on Sat, 1 Mar 2014, 19:29
//# Solve by: 291879
//# ---------------
//# 4613732
//# 4613732
//# [Finished in 0.2s]

public class Problem2 {

	public static void main(String[] args) {
		long f1 = 1, f2 = 2, saved;
		long sum = 0;
		
		while (f2 <= 4000000) {
			if (f2 % 2 == 0) sum += f2;
			saved = f1;
			f1 = f2;
			f2 = saved + f2;
		}
		
		System.out.println("The sum is: " + sum);
	}

}
